name: lint-and-build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint (tolère 10 warnings)
        run: npm run lint

      - name: Build web (Metro)
        run: npx expo export --platform web --output-dir dist
        env:
          EXPO_NO_TELEMETRY: "1"
          CI: "true"

      - name: Upload static web build
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist

