name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build web
        run: npm run build:web
        env:
          EXPO_NO_TELEMETRY: 1

      - name: Upload web artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web-build
