name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      EXPO_NO_TELEMETRY: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18.19
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: 'npm'

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Lint
        run: npx eslint "src/**/*.{ts,tsx}" --max-warnings=0

      - name: Build web
        run: npx expo export --platform web --output-dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
