name: Expo Web build

on: [push, pull_request]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          expo-cache: true
      - run: npx expo install --check                             # vérifie les deps sans les mettre à jour
      - run: npx expo export:web --skip-dependency-check
